<?php
/**
 * SSO - A single sign-on module for Sentora.
 * @author Bobby Allen (ballen@bobbyallen.me)
 * @copyright (c) 2015, Supared Limited
 * @link https://github.com/supared/sentora-sso
 * @license https://github.com/supared/sentora-sso/blob/master/LICENSE
 * @version 1.0.0
 */

/**
 * Removal of the SSO module config option from the Sentora settings table.
 */
$zdbh->exec("DELETE FROM x_settings WHERE so_name_vc = 'sso_config';");
